### ISSUE TITLE
FXTWITTER does NOT show the original size/resolution of the picture in the Twitter post, rather it shows a compressed version. Suggestion to fix this:

### ISSUE THREAD

**Issue by ILudw1g** [FxEmbed/FxEmbed#1282]
When you post a FXTWITTER link, looking at the raw data of the message of the FXTWITTER link in Discord, it mentions the URL for the image shown is e.g: 
"https://pbs.twimg.com/media/GpOC7WQagAA3LSc.jpg" (see image below) 

![Image](https://github.com/user-attachments/assets/5ad99adc-c272-49c2-a6c5-3428c600b0ef)

However, if you add "?format=jpg&name=orig" after this URL, the image shown will be the ORIGINAL size/resolution posted in the Twitter post. 
So if the URL in this case in the FXTWITTER link could be replaced with 

https://pbs.twimg.com/media/GpOC7WQagAA3LSc.jpg?format=jpg&name=orig
OR
https://pbs.twimg.com/media/GpOC7WQagAA3LSc?format=jpg&name=orig (replace ".jpg" with "?format=jpg&name=orig")

This should now show the full image. 

Please analyse what I have posted above and please see if you can make this change, as it will make the image quality much better... And I would very much appreciate it.

Thank you.

Some comparisons below:
"https://pbs.twimg.com/media/GpOC7WQagAA3LSc.jpg" (1200x675)

![Image](https://github.com/user-attachments/assets/1dd15c24-8fb0-4c18-bdc6-2673c9b6f565)

"https://pbs.twimg.com/media/GpOC7WQagAA3LSc?format=jpg&name=orig" AND "https://pbs.twimg.com/media/GpOC7WQagAA3LSc.jpg?format=jpg&name=orig" (1920x1080)

![Image](https://github.com/user-attachments/assets/c6034902-2b21-435c-a2f6-4386bbe7c552)

![Image](https://github.com/user-attachments/assets/95794f0e-c505-4603-ac9a-fc4a8e2fe7ab)

**Comment by pha1n0q** [comment]
~~Or even better, replace it with `?format=png&name=orig` (png instead of jpg) :P~~

nvm, that didn't work as expected, but `?format=png&name=large` works

**Comment by ILudw1g** [comment]
well currently fixupx is not working at all. hopefully this can be looked into soon, but I am currently using fixvx

**Comment by dangeredwolf** [comment]
It should be fixed now! It was borked for several hours earlier because they started blocking cloudflare's entire worker IP range

**Comment by ILudw1g** [comment]
thanks for that. would it possible if you could provide whether the change in this topic is possible, or when it could be implemented? thank you!

**Comment by dwahgon** [comment]
bumping cause this is still an issue.. the fxtwitter embed from discord, when opened in the browser or directly downloaded, still provides a very compressed version of the image instead of the original/large one if we simply let twitter.com handle the embed. testing it on a random post i got here, the difference in resolutions is 1200x991 and 2048x1692, def significant enough to impact the quality of an opened image preview

**Comment by ILudw1g** [comment]
thanks for the bump. i wonder if this can be implemented and how easy it would be to do so.

**Comment by dangeredwolf** [comment]
We now use the original quality images, and also use Discord's native multi-image instead of the combined mosaic so even multi-image posts benefit from the improved quality :D

**Comment by Yay295** [comment]
I've fixed it now, but this change broke my script because I wasn't expecting the image URL to have any query parameters.

https://xkcd.com/1172/

**Comment by dangeredwolf** [comment]
> I've fixed it now, but this change broke my script because I wasn't expecting the image URL to have any query parameters.
> 
> https://xkcd.com/1172/

@Yay295 Oh my god that's too funny hahaha

I did not anticipate this change to affect compatibility, this is literally the perfect xkcd comic. Glad it was an easy fix at least.
